version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/$REGISTRY_ALIAS
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/$REGISTRY_ALIAS/$REPO_NAME
  post_build:
    commands:
      - docker push public.ecr.aws/$REGISTRY_ALIAS/$REPO_NAME

