AWSTemplateFormatVersion: 2010-09-09

Description: CodeBuild infrastructure to build the Docker image for pdfconverter

Parameters:
  Architecture:
    Description: Architecture of the Docker image.
    Type: String
    Default: arm64
    AllowedValues:
    - arm64
    - x86
  ImageRepository:
    Description: Target ECR private repository of the Docker image. Must be in same region as this stack.
    Type: String
    Default: s3pdfconverter

Mappings:
  ArchitectureMap:
    EnvType:
      arm64: ARM_CONTAINER
      x86: LINUX_CONTAINER
    EnvImage:
      arm64: aws/codebuild/amazonlinux2-aarch64-standard:3.0
      x86: aws/codebuild/amazonlinux2-x86_64-standard:5.0

Resources:
  CodeBuildPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource:
          - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}:log-stream:*"
        - Action:
          - codestar-connections:UseConnection
          - codestar-connections:GetConnection
          Effect: Allow
          Resource:
          - !Sub "arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/*"
          - !Sub "arn:aws:codeconnections:${AWS::Region}:${AWS::AccountId}:connection/*"
        - Action:
          - codebuild:CreateReportGroup
          - codebuild:CreateReport
          - codebuild:UpdateReport
          - codebuild:BatchPutTestCases
          - codebuild:BatchPutCodeCoverages
          Effect: Allow
          Resource:
          - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*"
        - Action:
          - ecr:BatchCheckLayerAvailability
          - ecr:CompleteLayerUpload
          - ecr:GetAuthorizationToken
          - ecr:InitiateLayerUpload
          - ecr:PutImage
          - ecr:UploadLayerPart
          - ecr:CreateRepository
          Effect: Allow
          Resource: '*'
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicy
      Roles:
      - !Ref 'CodeBuildRole'
    Type: AWS::IAM::Policy

  CodeBuildProject:
    DependsOn:
    - CodeBuildPolicy
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Location: LOCAL
        Type: LOCAL
        Modes:
        - LOCAL_DOCKER_LAYER_CACHE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !FindInMap [ArchitectureMap, EnvImage, !Ref 'Architecture']
        Type: !FindInMap [ArchitectureMap, EnvType, !Ref 'Architecture']
        EnvironmentVariables:
        - Name: AWS_DEFAULT_REGION
          Type: PLAINTEXT
          Value: !Ref 'AWS::Region'
        - Name: AWS_ACCOUNT_ID
          Type: PLAINTEXT
          Value: !Ref 'AWS::AccountId'
        - Name: IMAGE_REPO_NAME
          Type: PLAINTEXT
          Value: !Ref 'ImageRepository'
        - Name: IMAGE_TAG
          Type: PLAINTEXT
          Value: !Sub
              - "${Architecture}-latest"
              - Architecture: !Ref 'Architecture'
      Name: !Ref 'AWS::StackName'
      ServiceRole: !Ref 'CodeBuildRole'
      Source:
        Type: GITHUB
        Location: https://github.com/ronfoerster/s3-pdf-converter.git
      TimeoutInMinutes: 20
    Type: AWS::CodeBuild::Project

  CodeBuildRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Path: /
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodeBuild
    Type: AWS::IAM::Role
